name: Build (Win32 Debug & Release — split symbols)

on:
  push:
    branches: [ main ]
    tags: [ '*' ]            # optional: also runs on tag push
  release:
    types: [published]       # runs when you click "Publish release"
  workflow_dispatch:

permissions:
  contents: write            # required to upload assets to a Release

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 8

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]   # build both

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure CMake (Win32)
        run: >
          cmake -S . -B ${{ github.workspace }}\build
          -G "Visual Studio 17 2022"
          -A Win32

      - name: Build (${{ matrix.config }})
        run: cmake --build ${{ github.workspace }}\build --config ${{ matrix.config }} -- /m

      # Upload CI artifacts (kept combined here for convenience)
      - name: Upload CI artifacts (${{ matrix.config }})
        uses: actions/upload-artifact@v4
        with:
          name: Aurora.Network-win32-${{ matrix.config }}
          path: |
            ${{ github.workspace }}\build\**\${{ matrix.config }}\*.dll
            ${{ github.workspace }}\build\**\${{ matrix.config }}\*.lib
            ${{ github.workspace }}\build\**\${{ matrix.config }}\*.pdb
            ${{ github.workspace }}\build\**\${{ matrix.config }}\*.exe
          if-no-files-found: warn

      # Package binaries and symbols separately for Release publishing
      - name: Package (${{ matrix.config }})
        if: github.event_name == 'release' && github.event.action == 'published'
        shell: pwsh
        run: |
          $cfg = "${{ matrix.config }}"
          $root = "${{ github.workspace }}"
          $build = "$root\build"
          $out = "$root\out\$cfg"
          New-Item -ItemType Directory -Force -Path "$out\binaries","$out\symbols" | Out-Null

          # Collect binaries for this config
          Get-ChildItem -Path $build -Recurse -Include *.dll,*.lib,*.exe |
            Where-Object { $_.FullName -match "\\$cfg\\" } |
            Copy-Item -Destination "$out\binaries" -Force

          # Collect symbols (PDBs) for this config
          Get-ChildItem -Path $build -Recurse -Include *.pdb |
            Where-Object { $_.FullName -match "\\$cfg\\" } |
            Copy-Item -Destination "$out\symbols" -Force

          # Zip with unique names per config
          $zipBin = "$root\out\Aurora.Network-win32-$cfg-binaries.zip"
          $zipSym = "$root\out\Aurora.Network-win32-$cfg-symbols.zip"
          if (Test-Path $zipBin) { Remove-Item $zipBin -Force }
          if (Test-Path $zipSym) { Remove-Item $zipSym -Force }
          Compress-Archive -Path "$out\binaries\*" -DestinationPath $zipBin
          Compress-Archive -Path "$out\symbols\*"  -DestinationPath $zipSym

      - name: Upload both zips to GitHub Release
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}\out\Aurora.Network-win32-Debug-binaries.zip
            ${{ github.workspace }}\out\Aurora.Network-win32-Debug-symbols.zip
            ${{ github.workspace }}\out\Aurora.Network-win32-Release-binaries.zip
            ${{ github.workspace }}\out\Aurora.Network-win32-Release-symbols.zip
