name: Build (Win32 Debug & Release)

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]

    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Configure CMake (Win32)
        run: >
          cmake -S . -B ${{ github.workspace }}\build
          -G "Visual Studio 17 2022"
          -A Win32

      - name: Build (${{ matrix.config }})
        run: cmake --build ${{ github.workspace }}\build --config ${{ matrix.config }} -- /m

      - name: Upload artifacts (${{ matrix.config }})
        uses: actions/upload-artifact@v4
        with:
          name: Aurora.Network-win32-${{ matrix.config }}
          path: |
            ${{ github.workspace }}\build\**\${{ matrix.config }}\*.dll
            ${{ github.workspace }}\build\**\${{ matrix.config }}\*.lib
            ${{ github.workspace }}\build\**\${{ matrix.config }}\*.pdb
            ${{ github.workspace }}\build\**\${{ matrix.config }}\*.exe
          if-no-files-found: warn

      - name: Create GitHub Release (Release config only)
        if: startsWith(github.ref, 'refs/tags/') && matrix.config == 'Release' && success()
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}\build\Code\Proxy\Release\Aurora.Network.dll

